// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyB3IOtsMvsWl4njOi1D0_ZRjDou57IN8XY',
  //   appId: '1:521060811471:web:d8e8054b3dec934bc3adba',
  //   messagingSenderId: '521060811471',
  //   projectId: 'gorinsystems-3fbdd',
  //   authDomain: 'gorinsystems-3fbdd.firebaseapp.com',
  //   storageBucket: 'gorinsystems-3fbdd.appspot.com',
  //   measurementId: 'G-N7ZSSWFY92',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpoZ9H0Msa20hbwRuOh0fvT-HHQ9goSTg',
    appId: '1:521060811471:android:3e28363f1bca8f89c3adba',
    messagingSenderId: '521060811471',
    projectId: 'gorinsystems-3fbdd',
    storageBucket: 'gorinsystems-3fbdd.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDXcIYbeS2uqS73B4LT5I_zvLzEJLWfW20',
  //   appId: '1:521060811471:ios:7682f73f9547e85cc3adba',
  //   messagingSenderId: '521060811471',
  //   projectId: 'gorinsystems-3fbdd',
  //   storageBucket: 'gorinsystems-3fbdd.appspot.com',
  //   iosBundleId: 'com.test1.testApp',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDXcIYbeS2uqS73B4LT5I_zvLzEJLWfW20',
  //   appId: '1:521060811471:ios:b1eaa48b2a6afaa9c3adba',
  //   messagingSenderId: '521060811471',
  //   projectId: 'gorinsystems-3fbdd',
  //   storageBucket: 'gorinsystems-3fbdd.appspot.com',
  //   iosBundleId: 'com.test1.testApp.RunnerTests',
  // );
}
